////////////////////////////////////////////////////////////
// KeySqr Specification Cpp (NOT TO BE MODIFIED DIRECTLY!)
////////////////////////////////////////////////////////////
//
// This file is generated automatically by the KeySqr
// specification generator, which is written in TypeScript.

#include "keysqr-element-face-specification.h"
#include <assert.h>

const std::string ElementLetters = "ABCDEFGHIJKLMNOPRSTUVWXYZ";
const std::string ElementDigits = "123456";

const ElementFaceSpecification NullElementFaceSpecification = {'\0', '\0', 0, 0};

namespace ElemmentDimensionsFractional {
  const std::vector<float> dotCentersAsFractionOfUndoverline = {
    float(0.0967741935483871),
    float(0.1774193548387097),
    float(0.25806451612903225),
    float(0.33870967741935487),
    float(0.41935483870967744),
    float(0.5),
    float(0.5806451612903226),
    float(0.6612903225806451),
    float(0.7419354838709676),
    float(0.8225806451612903),
    float(0.9032258064516128),
  };
};

const ElementFaceSpecification letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[150] = {	{'A', '1', 0x7, 0xe9},
	{'A', '2', 0xb, 0xf1},
	{'A', '3', 0xd, 0xe0},
	{'A', '4', 0x16, 0xf2},
	{'A', '5', 0x1a, 0xea},
	{'A', '6', 0x1e, 0xe1},
	{'B', '1', 0x1f, 0xe6},
	{'B', '2', 0x26, 0xc3},
	{'B', '3', 0x27, 0xc4},
	{'B', '4', 0x29, 0xc6},
	{'B', '5', 0x2b, 0xdc},
	{'B', '6', 0x2c, 0xca},
	{'C', '1', 0x2d, 0xcd},
	{'C', '2', 0x2e, 0xd0},
	{'C', '3', 0x31, 0xc9},
	{'C', '4', 0x32, 0xd4},
	{'C', '5', 0x33, 0xd3},
	{'C', '6', 0x34, 0xc5},
	{'D', '1', 0x35, 0xc2},
	{'D', '2', 0x37, 0xd8},
	{'D', '3', 0x39, 0xda},
	{'D', '4', 0x3a, 0xc7},
	{'D', '5', 0x3b, 0xc0},
	{'D', '6', 0x3c, 0xd6},
	{'E', '1', 0x3d, 0xd1},
	{'E', '2', 0x3e, 0xcc},
	{'E', '3', 0x3f, 0xcb},
	{'E', '4', 0x45, 0xa6},
	{'E', '5', 0x47, 0xbc},
	{'E', '6', 0x4a, 0xa3},
	{'F', '1', 0x4b, 0xa4},
	{'F', '2', 0x4c, 0xb2},
	{'F', '3', 0x4d, 0xb5},
	{'F', '4', 0x4e, 0xa8},
	{'F', '5', 0x51, 0xb1},
	{'F', '6', 0x52, 0xac},
	{'G', '1', 0x53, 0xab},
	{'G', '2', 0x55, 0xba},
	{'G', '3', 0x56, 0xa7},
	{'G', '4', 0x57, 0xa0},
	{'G', '5', 0x58, 0xa5},
	{'G', '6', 0x59, 0xa2},
	{'H', '1', 0x5b, 0xb8},
	{'H', '2', 0x5c, 0xae},
	{'H', '3', 0x5d, 0xa9},
	{'H', '4', 0x5e, 0xb4},
	{'H', '5', 0x5f, 0xb3},
	{'H', '6', 0x62, 0x9d},
	{'I', '1', 0x63, 0x9a},
	{'I', '2', 0x64, 0x8c},
	{'I', '3', 0x65, 0x8b},
	{'I', '4', 0x66, 0x96},
	{'I', '5', 0x67, 0x91},
	{'I', '6', 0x68, 0x94},
	{'J', '1', 0x69, 0x93},
	{'J', '2', 0x6a, 0x8e},
	{'J', '3', 0x6b, 0x89},
	{'J', '4', 0x6d, 0x98},
	{'J', '5', 0x6e, 0x85},
	{'J', '6', 0x6f, 0x82},
	{'K', '1', 0x70, 0x9b},
	{'K', '2', 0x71, 0x9c},
	{'K', '3', 0x72, 0x81},
	{'K', '4', 0x73, 0x86},
	{'K', '5', 0x74, 0x90},
	{'K', '6', 0x75, 0x97},
	{'L', '1', 0x76, 0x8a},
	{'L', '2', 0x77, 0x8d},
	{'L', '3', 0x78, 0x88},
	{'L', '4', 0x79, 0x8f},
	{'L', '5', 0x7a, 0x92},
	{'L', '6', 0x7b, 0x95},
	{'M', '1', 0x7c, 0x83},
	{'M', '2', 0x7d, 0x84},
	{'M', '3', 0x7e, 0x99},
	{'M', '4', 0x85, 0x6a},
	{'M', '5', 0x87, 0x70},
	{'M', '6', 0x89, 0x72},
	{'N', '1', 0x8b, 0x68},
	{'N', '2', 0x8d, 0x79},
	{'N', '3', 0x8e, 0x64},
	{'N', '4', 0x8f, 0x63},
	{'N', '5', 0x92, 0x60},
	{'N', '6', 0x93, 0x67},
	{'O', '1', 0x94, 0x71},
	{'O', '2', 0x95, 0x76},
	{'O', '3', 0x96, 0x6b},
	{'O', '4', 0x97, 0x6c},
	{'O', '5', 0x98, 0x69},
	{'O', '6', 0x99, 0x6e},
	{'P', '1', 0x9a, 0x73},
	{'P', '2', 0x9b, 0x74},
	{'P', '3', 0x9c, 0x62},
	{'P', '4', 0x9d, 0x65},
	{'P', '5', 0x9e, 0x78},
	{'P', '6', 0xa1, 0x4c},
	{'R', '1', 0xa2, 0x51},
	{'R', '2', 0xa3, 0x56},
	{'R', '3', 0xa5, 0x47},
	{'R', '4', 0xa6, 0x5a},
	{'R', '5', 0xa7, 0x5d},
	{'R', '6', 0xa8, 0x58},
	{'S', '1', 0xaa, 0x42},
	{'S', '2', 0xab, 0x45},
	{'S', '3', 0xac, 0x53},
	{'S', '4', 0xad, 0x54},
	{'S', '5', 0xae, 0x49},
	{'S', '6', 0xaf, 0x4e},
	{'T', '1', 0xb0, 0x57},
	{'T', '2', 0xb1, 0x50},
	{'T', '3', 0xb2, 0x4d},
	{'T', '4', 0xb3, 0x4a},
	{'T', '5', 0xb4, 0x5c},
	{'T', '6', 0xb5, 0x5b},
	{'U', '1', 0xb6, 0x46},
	{'U', '2', 0xb7, 0x41},
	{'U', '3', 0xb8, 0x44},
	{'U', '4', 0xb9, 0x43},
	{'U', '5', 0xba, 0x5e},
	{'U', '6', 0xbb, 0x59},
	{'V', '1', 0xbc, 0x4f},
	{'V', '2', 0xbd, 0x48},
	{'V', '3', 0xbe, 0x55},
	{'V', '4', 0xc1, 0x34},
	{'V', '5', 0xc2, 0x29},
	{'V', '6', 0xc3, 0x2e},
	{'W', '1', 0xc4, 0x38},
	{'W', '2', 0xc6, 0x22},
	{'W', '3', 0xc7, 0x25},
	{'W', '4', 0xc9, 0x27},
	{'W', '5', 0xca, 0x3a},
	{'W', '6', 0xcb, 0x3d},
	{'X', '1', 0xcc, 0x2b},
	{'X', '2', 0xcd, 0x2c},
	{'X', '3', 0xce, 0x31},
	{'X', '4', 0xcf, 0x36},
	{'X', '5', 0xd0, 0x2f},
	{'X', '6', 0xd1, 0x28},
	{'Y', '1', 0xd2, 0x35},
	{'Y', '2', 0xd3, 0x32},
	{'Y', '3', 0xd4, 0x24},
	{'Y', '4', 0xd5, 0x23},
	{'Y', '5', 0xd6, 0x3e},
	{'Y', '6', 0xd7, 0x39},
	{'Z', '1', 0xd8, 0x3c},
	{'Z', '2', 0xd9, 0x3b},
	{'Z', '3', 0xda, 0x26},
	{'Z', '4', 0xdb, 0x21},
	{'Z', '5', 0xdc, 0x37},
	{'Z', '6', 0xdd, 0x30}
};

const ElementFaceSpecification* underlineCodeToElementFaceSpecification[256] = {
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[0]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[1]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[2]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[3]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[4]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[5]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[6]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[7]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[8]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[9]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[10]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[11]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[12]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[13]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[14]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[15]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[16]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[17]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[18]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[19]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[20]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[21]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[22]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[23]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[24]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[25]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[26]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[27]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[28]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[29]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[30]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[31]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[32]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[33]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[34]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[35]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[36]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[37]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[38]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[39]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[40]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[41]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[42]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[43]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[44]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[45]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[46]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[47]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[48]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[49]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[50]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[51]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[52]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[53]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[54]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[55]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[56]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[57]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[58]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[59]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[60]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[61]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[62]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[63]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[64]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[65]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[66]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[67]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[68]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[69]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[70]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[71]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[72]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[73]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[74]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[75]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[76]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[77]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[78]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[79]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[80]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[81]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[82]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[83]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[84]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[85]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[86]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[87]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[88]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[89]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[90]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[91]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[92]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[93]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[94]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[95]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[96]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[97]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[98]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[99]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[100]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[101]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[102]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[103]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[104]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[105]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[106]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[107]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[108]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[109]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[110]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[111]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[112]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[113]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[114]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[115]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[116]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[117]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[118]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[119]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[120]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[121]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[122]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[123]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[124]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[125]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[126]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[127]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[128]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[129]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[130]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[131]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[132]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[133]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[134]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[135]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[136]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[137]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[138]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[139]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[140]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[141]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[142]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[143]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[144]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[145]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[146]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[147]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[148]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[149]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification
};

const ElementFaceSpecification* overlineCodeToElementFaceSpecification[256] = {
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[147]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[127]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[141]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[140]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[128]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[146]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[129]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[137]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[124]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[132]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[133]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[125]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[136]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[149]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[134]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[139]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[123]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[138]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[135]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[148]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[126]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[143]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[130]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[145]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[144]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[131]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[142]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[115]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[102]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[117]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[116]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[103]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[114]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[98]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[121]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[106]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[111]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[95]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[110]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[107]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[120]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[109]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[96]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[104]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[105]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[122]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[97]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[108]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[101]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[119]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[99]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[113]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[112]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[100]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[118]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[82]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[92]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[81]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[80]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[93]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[83]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[78]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[88]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[75]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[86]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[87]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[89]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[76]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[84]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[77]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[90]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[91]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[85]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[94]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[79]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[62]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[59]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[72]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[73]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[58]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[63]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[68]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[56]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[66]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[50]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[49]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[67]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[55]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[69]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[64]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[52]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[70]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[54]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[53]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[71]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[51]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[65]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[57]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[74]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[48]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[60]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[61]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[47]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[39]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[41]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[29]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[30]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[40]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[27]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[38]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[33]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[44]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[36]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[35]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[43]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[34]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[31]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[46]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[45]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[32]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[42]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[37]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[28]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[22]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[18]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[7]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[8]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[17]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[9]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[21]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[14]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[11]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[26]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[25]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[12]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[13]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[24]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[16]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[15]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[23]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[19]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[20]),
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[10]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[2]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[5]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[6]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[0]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[4]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[1]),
	&(letterIndexTimesSixPlusDigitIndexToElementFaceSpecification[3]),
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification,
	&NullElementFaceSpecification
};

const ElementFaceSpecification* decodeUndoverlineByte(bool isOverline, unsigned char letterDigitEncodingByte) {
  return isOverline ?
		overlineCodeToElementFaceSpecification[letterDigitEncodingByte] :
		underlineCodeToElementFaceSpecification[letterDigitEncodingByte];
}
