////////////////////////////////////////////////////////////
// DiceKeys Specification Cpp (NOT TO BE MODIFIED DIRECTLY!)
////////////////////////////////////////////////////////////
//
// This file is generated automatically by the DiceKey
// specification generator, which is written in TypeScript.

#include "dice-specification.h"
#include <assert.h>

const DieFaceSpecification letterIndexTimesSixPlusDigitIndexToDieFaceSpecification[150] = { 'A', '1', 0x7, 0xe9,
	'A', '2', 0xb, 0xf1,
	'A', '3', 0xd, 0xe0,
	'A', '4', 0x16, 0xf2,
	'A', '5', 0x1a, 0xea,
	'A', '6', 0x1e, 0xe1,
	'B', '1', 0x1f, 0xe6,
	'B', '2', 0x26, 0xc3,
	'B', '3', 0x27, 0xc4,
	'B', '4', 0x29, 0xc6,
	'B', '5', 0x2b, 0xdc,
	'B', '6', 0x2c, 0xca,
	'C', '1', 0x2d, 0xcd,
	'C', '2', 0x2e, 0xd0,
	'C', '3', 0x31, 0xc9,
	'C', '4', 0x32, 0xd4,
	'C', '5', 0x33, 0xd3,
	'C', '6', 0x34, 0xc5,
	'D', '1', 0x35, 0xc2,
	'D', '2', 0x37, 0xd8,
	'D', '3', 0x39, 0xda,
	'D', '4', 0x3a, 0xc7,
	'D', '5', 0x3b, 0xc0,
	'D', '6', 0x3c, 0xd6,
	'E', '1', 0x3d, 0xd1,
	'E', '2', 0x3e, 0xcc,
	'E', '3', 0x3f, 0xcb,
	'E', '4', 0x45, 0xa6,
	'E', '5', 0x47, 0xbc,
	'E', '6', 0x4a, 0xa3,
	'F', '1', 0x4b, 0xa4,
	'F', '2', 0x4c, 0xb2,
	'F', '3', 0x4d, 0xb5,
	'F', '4', 0x4e, 0xa8,
	'F', '5', 0x51, 0xb1,
	'F', '6', 0x52, 0xac,
	'G', '1', 0x53, 0xab,
	'G', '2', 0x55, 0xba,
	'G', '3', 0x56, 0xa7,
	'G', '4', 0x57, 0xa0,
	'G', '5', 0x58, 0xa5,
	'G', '6', 0x59, 0xa2,
	'H', '1', 0x5b, 0xb8,
	'H', '2', 0x5c, 0xae,
	'H', '3', 0x5d, 0xa9,
	'H', '4', 0x5e, 0xb4,
	'H', '5', 0x5f, 0xb3,
	'H', '6', 0x62, 0x9d,
	'I', '1', 0x63, 0x9a,
	'I', '2', 0x64, 0x8c,
	'I', '3', 0x65, 0x8b,
	'I', '4', 0x66, 0x96,
	'I', '5', 0x67, 0x91,
	'I', '6', 0x68, 0x94,
	'J', '1', 0x69, 0x93,
	'J', '2', 0x6a, 0x8e,
	'J', '3', 0x6b, 0x89,
	'J', '4', 0x6d, 0x98,
	'J', '5', 0x6e, 0x85,
	'J', '6', 0x6f, 0x82,
	'K', '1', 0x70, 0x9b,
	'K', '2', 0x71, 0x9c,
	'K', '3', 0x72, 0x81,
	'K', '4', 0x73, 0x86,
	'K', '5', 0x74, 0x90,
	'K', '6', 0x75, 0x97,
	'L', '1', 0x76, 0x8a,
	'L', '2', 0x77, 0x8d,
	'L', '3', 0x78, 0x88,
	'L', '4', 0x79, 0x8f,
	'L', '5', 0x7a, 0x92,
	'L', '6', 0x7b, 0x95,
	'M', '1', 0x7c, 0x83,
	'M', '2', 0x7d, 0x84,
	'M', '3', 0x7e, 0x99,
	'M', '4', 0x85, 0x6a,
	'M', '5', 0x87, 0x70,
	'M', '6', 0x89, 0x72,
	'N', '1', 0x8b, 0x68,
	'N', '2', 0x8d, 0x79,
	'N', '3', 0x8e, 0x64,
	'N', '4', 0x8f, 0x63,
	'N', '5', 0x92, 0x60,
	'N', '6', 0x93, 0x67,
	'O', '1', 0x94, 0x71,
	'O', '2', 0x95, 0x76,
	'O', '3', 0x96, 0x6b,
	'O', '4', 0x97, 0x6c,
	'O', '5', 0x98, 0x69,
	'O', '6', 0x99, 0x6e,
	'P', '1', 0x9a, 0x73,
	'P', '2', 0x9b, 0x74,
	'P', '3', 0x9c, 0x62,
	'P', '4', 0x9d, 0x65,
	'P', '5', 0x9e, 0x78,
	'P', '6', 0xa1, 0x4c,
	'R', '1', 0xa2, 0x51,
	'R', '2', 0xa3, 0x56,
	'R', '3', 0xa5, 0x47,
	'R', '4', 0xa6, 0x5a,
	'R', '5', 0xa7, 0x5d,
	'R', '6', 0xa8, 0x58,
	'S', '1', 0xaa, 0x42,
	'S', '2', 0xab, 0x45,
	'S', '3', 0xac, 0x53,
	'S', '4', 0xad, 0x54,
	'S', '5', 0xae, 0x49,
	'S', '6', 0xaf, 0x4e,
	'T', '1', 0xb0, 0x57,
	'T', '2', 0xb1, 0x50,
	'T', '3', 0xb2, 0x4d,
	'T', '4', 0xb3, 0x4a,
	'T', '5', 0xb4, 0x5c,
	'T', '6', 0xb5, 0x5b,
	'U', '1', 0xb6, 0x46,
	'U', '2', 0xb7, 0x41,
	'U', '3', 0xb8, 0x44,
	'U', '4', 0xb9, 0x43,
	'U', '5', 0xba, 0x5e,
	'U', '6', 0xbb, 0x59,
	'V', '1', 0xbc, 0x4f,
	'V', '2', 0xbd, 0x48,
	'V', '3', 0xbe, 0x55,
	'V', '4', 0xc1, 0x34,
	'V', '5', 0xc2, 0x29,
	'V', '6', 0xc3, 0x2e,
	'W', '1', 0xc4, 0x38,
	'W', '2', 0xc6, 0x22,
	'W', '3', 0xc7, 0x25,
	'W', '4', 0xc9, 0x27,
	'W', '5', 0xca, 0x3a,
	'W', '6', 0xcb, 0x3d,
	'X', '1', 0xcc, 0x2b,
	'X', '2', 0xcd, 0x2c,
	'X', '3', 0xce, 0x31,
	'X', '4', 0xcf, 0x36,
	'X', '5', 0xd0, 0x2f,
	'X', '6', 0xd1, 0x28,
	'Y', '1', 0xd2, 0x35,
	'Y', '2', 0xd3, 0x32,
	'Y', '3', 0xd4, 0x24,
	'Y', '4', 0xd5, 0x23,
	'Y', '5', 0xd6, 0x3e,
	'Y', '6', 0xd7, 0x39,
	'Z', '1', 0xd8, 0x3c,
	'Z', '2', 0xd9, 0x3b,
	'Z', '3', 0xda, 0x26,
	'Z', '4', 0xdb, 0x21,
	'Z', '5', 0xdc, 0x37,
	'Z', '6', 0xdd, 0x30
};


const DieFaceSpecification letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[150] = { 'A', '1', 0x7, 0xe9,
	'A', '2', 0xb, 0xf1,
	'A', '3', 0xd, 0xe0,
	'A', '4', 0x16, 0xf2,
	'A', '5', 0x1a, 0xea,
	'A', '6', 0x1e, 0xe1,
	'B', '1', 0x1f, 0xe6,
	'B', '2', 0x26, 0xc3,
	'B', '3', 0x27, 0xc4,
	'B', '4', 0x29, 0xc6,
	'B', '5', 0x2b, 0xdc,
	'B', '6', 0x2c, 0xca,
	'C', '1', 0x2d, 0xcd,
	'C', '2', 0x2e, 0xd0,
	'C', '3', 0x31, 0xc9,
	'C', '4', 0x32, 0xd4,
	'C', '5', 0x33, 0xd3,
	'C', '6', 0x34, 0xc5,
	'D', '1', 0x35, 0xc2,
	'D', '2', 0x37, 0xd8,
	'D', '3', 0x39, 0xda,
	'D', '4', 0x3a, 0xc7,
	'D', '5', 0x3b, 0xc0,
	'D', '6', 0x3c, 0xd6,
	'E', '1', 0x3d, 0xd1,
	'E', '2', 0x3e, 0xcc,
	'E', '3', 0x3f, 0xcb,
	'E', '4', 0x45, 0xa6,
	'E', '5', 0x47, 0xbc,
	'E', '6', 0x4a, 0xa3,
	'F', '1', 0x4b, 0xa4,
	'F', '2', 0x4c, 0xb2,
	'F', '3', 0x4d, 0xb5,
	'F', '4', 0x4e, 0xa8,
	'F', '5', 0x51, 0xb1,
	'F', '6', 0x52, 0xac,
	'G', '1', 0x53, 0xab,
	'G', '2', 0x55, 0xba,
	'G', '3', 0x56, 0xa7,
	'G', '4', 0x57, 0xa0,
	'G', '5', 0x58, 0xa5,
	'G', '6', 0x59, 0xa2,
	'H', '1', 0x5b, 0xb8,
	'H', '2', 0x5c, 0xae,
	'H', '3', 0x5d, 0xa9,
	'H', '4', 0x5e, 0xb4,
	'H', '5', 0x5f, 0xb3,
	'H', '6', 0x62, 0x9d,
	'I', '1', 0x63, 0x9a,
	'I', '2', 0x64, 0x8c,
	'I', '3', 0x65, 0x8b,
	'I', '4', 0x66, 0x96,
	'I', '5', 0x67, 0x91,
	'I', '6', 0x68, 0x94,
	'J', '1', 0x69, 0x93,
	'J', '2', 0x6a, 0x8e,
	'J', '3', 0x6b, 0x89,
	'J', '4', 0x6d, 0x98,
	'J', '5', 0x6e, 0x85,
	'J', '6', 0x6f, 0x82,
	'K', '1', 0x70, 0x9b,
	'K', '2', 0x71, 0x9c,
	'K', '3', 0x72, 0x81,
	'K', '4', 0x73, 0x86,
	'K', '5', 0x74, 0x90,
	'K', '6', 0x75, 0x97,
	'L', '1', 0x76, 0x8a,
	'L', '2', 0x77, 0x8d,
	'L', '3', 0x78, 0x88,
	'L', '4', 0x79, 0x8f,
	'L', '5', 0x7a, 0x92,
	'L', '6', 0x7b, 0x95,
	'M', '1', 0x7c, 0x83,
	'M', '2', 0x7d, 0x84,
	'M', '3', 0x7e, 0x99,
	'M', '4', 0x85, 0x6a,
	'M', '5', 0x87, 0x70,
	'M', '6', 0x89, 0x72,
	'N', '1', 0x8b, 0x68,
	'N', '2', 0x8d, 0x79,
	'N', '3', 0x8e, 0x64,
	'N', '4', 0x8f, 0x63,
	'N', '5', 0x92, 0x60,
	'N', '6', 0x93, 0x67,
	'O', '1', 0x94, 0x71,
	'O', '2', 0x95, 0x76,
	'O', '3', 0x96, 0x6b,
	'O', '4', 0x97, 0x6c,
	'O', '5', 0x98, 0x69,
	'O', '6', 0x99, 0x6e,
	'P', '1', 0x9a, 0x73,
	'P', '2', 0x9b, 0x74,
	'P', '3', 0x9c, 0x62,
	'P', '4', 0x9d, 0x65,
	'P', '5', 0x9e, 0x78,
	'P', '6', 0xa1, 0x4c,
	'R', '1', 0xa2, 0x51,
	'R', '2', 0xa3, 0x56,
	'R', '3', 0xa5, 0x47,
	'R', '4', 0xa6, 0x5a,
	'R', '5', 0xa7, 0x5d,
	'R', '6', 0xa8, 0x58,
	'S', '1', 0xaa, 0x42,
	'S', '2', 0xab, 0x45,
	'S', '3', 0xac, 0x53,
	'S', '4', 0xad, 0x54,
	'S', '5', 0xae, 0x49,
	'S', '6', 0xaf, 0x4e,
	'T', '1', 0xb0, 0x57,
	'T', '2', 0xb1, 0x50,
	'T', '3', 0xb2, 0x4d,
	'T', '4', 0xb3, 0x4a,
	'T', '5', 0xb4, 0x5c,
	'T', '6', 0xb5, 0x5b,
	'U', '1', 0xb6, 0x46,
	'U', '2', 0xb7, 0x41,
	'U', '3', 0xb8, 0x44,
	'U', '4', 0xb9, 0x43,
	'U', '5', 0xba, 0x5e,
	'U', '6', 0xbb, 0x59,
	'V', '1', 0xbc, 0x4f,
	'V', '2', 0xbd, 0x48,
	'V', '3', 0xbe, 0x55,
	'V', '4', 0xc1, 0x34,
	'V', '5', 0xc2, 0x29,
	'V', '6', 0xc3, 0x2e,
	'W', '1', 0xc4, 0x38,
	'W', '2', 0xc6, 0x22,
	'W', '3', 0xc7, 0x25,
	'W', '4', 0xc9, 0x27,
	'W', '5', 0xca, 0x3a,
	'W', '6', 0xcb, 0x3d,
	'X', '1', 0xcc, 0x2b,
	'X', '2', 0xcd, 0x2c,
	'X', '3', 0xce, 0x31,
	'X', '4', 0xcf, 0x36,
	'X', '5', 0xd0, 0x2f,
	'X', '6', 0xd1, 0x28,
	'Y', '1', 0xd2, 0x35,
	'Y', '2', 0xd3, 0x32,
	'Y', '3', 0xd4, 0x24,
	'Y', '4', 0xd5, 0x23,
	'Y', '5', 0xd6, 0x3e,
	'Y', '6', 0xd7, 0x39,
	'Z', '1', 0xd8, 0x3c,
	'Z', '2', 0xd9, 0x3b,
	'Z', '3', 0xda, 0x26,
	'Z', '4', 0xdb, 0x21,
	'Z', '5', 0xdc, 0x37,
	'Z', '6', 0xdd, 0x30
};


const DieFaceSpecification* underlineCodeToDieFaceSpecificationConst[256] = {
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[0]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[1]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[2]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[3]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[4]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[5]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[6]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[7]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[8]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[9]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[10]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[11]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[12]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[13]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[14]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[15]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[16]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[17]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[18]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[19]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[20]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[21]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[22]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[23]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[24]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[25]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[26]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[27]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[28]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[29]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[30]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[31]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[32]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[33]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[34]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[35]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[36]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[37]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[38]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[39]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[40]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[41]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[42]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[43]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[44]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[45]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[46]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[47]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[48]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[49]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[50]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[51]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[52]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[53]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[54]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[55]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[56]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[57]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[58]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[59]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[60]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[61]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[62]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[63]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[64]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[65]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[66]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[67]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[68]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[69]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[70]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[71]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[72]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[73]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[74]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[75]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[76]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[77]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[78]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[79]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[80]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[81]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[82]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[83]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[84]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[85]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[86]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[87]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[88]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[89]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[90]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[91]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[92]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[93]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[94]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[95]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[96]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[97]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[98]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[99]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[100]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[101]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[102]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[103]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[104]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[105]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[106]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[107]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[108]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[109]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[110]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[111]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[112]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[113]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[114]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[115]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[116]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[117]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[118]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[119]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[120]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[121]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[122]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[123]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[124]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[125]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[126]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[127]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[128]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[129]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[130]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[131]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[132]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[133]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[134]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[135]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[136]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[137]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[138]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[139]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[140]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[141]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[142]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[143]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[144]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[145]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[146]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[147]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[148]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[149]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification
};

const DieFaceSpecification* overlineCodeToDieFaceSpecificationConst[256] = {
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[147]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[127]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[141]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[140]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[128]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[146]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[129]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[137]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[124]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[132]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[133]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[125]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[136]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[149]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[134]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[139]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[123]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[138]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[135]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[148]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[126]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[143]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[130]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[145]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[144]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[131]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[142]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[115]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[102]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[117]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[116]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[103]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[114]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[98]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[121]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[106]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[111]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[95]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[110]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[107]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[120]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[109]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[96]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[104]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[105]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[122]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[97]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[108]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[101]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[119]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[99]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[113]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[112]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[100]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[118]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[82]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[92]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[81]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[80]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[93]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[83]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[78]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[88]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[75]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[86]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[87]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[89]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[76]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[84]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[77]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[90]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[91]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[85]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[94]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[79]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[62]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[59]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[72]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[73]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[58]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[63]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[68]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[56]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[66]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[50]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[49]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[67]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[55]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[69]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[64]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[52]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[70]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[54]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[53]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[71]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[51]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[65]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[57]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[74]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[48]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[60]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[61]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[47]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[39]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[41]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[29]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[30]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[40]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[27]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[38]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[33]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[44]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[36]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[35]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[43]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[34]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[31]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[46]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[45]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[32]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[42]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[37]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[28]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[22]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[18]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[7]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[8]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[17]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[9]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[21]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[14]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[11]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[26]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[25]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[12]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[13]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[24]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[16]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[15]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[23]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[19]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[20]),
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[10]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[2]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[5]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[6]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[0]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[4]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[1]),
	&(letterIndexTimesSixPlusDigitIndexToDieFaceSpecificationConst[3]),
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification,
	&NullDieFaceSpecification
};

const DieFaceSpecification* decodeUndoverlineByte(bool isOverline, unsigned char letterDigitEncodingByte) {
	assert(letterDigitEncodingByte < 256);
	return isOverline ?
		overlineCodeToDieFaceSpecificationConst[letterDigitEncodingByte] :
		underlineCodeToDieFaceSpecificationConst[letterDigitEncodingByte];
}
